package seeders

import (
	"fmt"
	"goravel/app/models"

	"github.com/goravel/framework/facades"
)

type CountrySeeder struct {
}

// Signature The name and signature of the seeder.
func (s *CountrySeeder) Signature() string {
	return "CountrySeeder"
}

// Run executes the seeder logic.
func (s *CountrySeeder) Run() error {
	facades.Log().Info(fmt.Sprintf("%s started", s.Signature()))
	defer facades.Log().Info(fmt.Sprintf("%s completed", s.Signature()))
	// Check if countries already exist
	var existingCountries []models.Country
	err := facades.Orm().Query().Limit(1).Find(&existingCountries)
	if err == nil && len(existingCountries) > 0 {
		facades.Log().Info("Countries already exist, skipping CountrySeeder")
		return nil
	}

	// Create countries
	countries := []models.Country{
		{
			Name:        "United States",
			Code:        "US",
			Code3:       "USA",
			NumericCode: "840",
			IsActive:    true,
		},
		{
			Name:        "Canada",
			Code:        "CA",
			Code3:       "CAN",
			NumericCode: "124",
			IsActive:    true,
		},
		{
			Name:        "United Kingdom",
			Code:        "GB",
			Code3:       "GBR",
			NumericCode: "826",
			IsActive:    true,
		},
		{
			Name:        "Germany",
			Code:        "DE",
			Code3:       "DEU",
			NumericCode: "276",
			IsActive:    true,
		},
		{
			Name:        "France",
			Code:        "FR",
			Code3:       "FRA",
			NumericCode: "250",
			IsActive:    true,
		},
		{
			Name:        "Japan",
			Code:        "JP",
			Code3:       "JPN",
			NumericCode: "392",
			IsActive:    true,
		},
		{
			Name:        "Australia",
			Code:        "AU",
			Code3:       "AUS",
			NumericCode: "036",
			IsActive:    true,
		},
		{
			Name:        "Brazil",
			Code:        "BR",
			Code3:       "BRA",
			NumericCode: "076",
			IsActive:    true,
		},
		{
			Name:        "India",
			Code:        "IN",
			Code3:       "IND",
			NumericCode: "356",
			IsActive:    true,
		},
		{
			Name:        "China",
			Code:        "CN",
			Code3:       "CHN",
			NumericCode: "156",
			IsActive:    true,
		},
		{
			Name:        "Indonesia",
			Code:        "ID",
			Code3:       "IDN",
			NumericCode: "360",
			IsActive:    true,
		},
		{
			Name:        "Singapore",
			Code:        "SG",
			Code3:       "SGP",
			NumericCode: "702",
			IsActive:    true,
		},
		{
			Name:        "Malaysia",
			Code:        "MY",
			Code3:       "MYS",
			NumericCode: "458",
			IsActive:    true,
		},
		{
			Name:        "Philippines",
			Code:        "PH",
			Code3:       "PHL",
			NumericCode: "608",
			IsActive:    true,
		},
		{
			Name:        "Thailand",
			Code:        "TH",
			Code3:       "THA",
			NumericCode: "764",
			IsActive:    true,
		},
		{
			Name:        "Vietnam",
			Code:        "VN",
			Code3:       "VNM",
			NumericCode: "704",
			IsActive:    true,
		},
		{
			Name:        "Brunei",
			Code:        "BN",
			Code3:       "BRN",
			NumericCode: "096",
			IsActive:    true,
		},
		{
			Name:        "Cambodia",
			Code:        "KH",
			Code3:       "KHM",
			NumericCode: "116",
			IsActive:    true,
		},
		{
			Name:        "Laos",
			Code:        "LA",
			Code3:       "LAO",
			NumericCode: "418",
			IsActive:    true,
		},
		{
			Name:        "Myanmar",
			Code:        "MM",
			Code3:       "MMR",
			NumericCode: "104",
			IsActive:    true,
		},
		{
			Name:        "Timor-Leste",
			Code:        "TL",
			Code3:       "TLS",
			NumericCode: "626",
			IsActive:    true,
		},
		{
			Name:        "South Korea",
			Code:        "KR",
			Code3:       "KOR",
			NumericCode: "410",
			IsActive:    true,
		},
		{
			Name:        "Mongolia",
			Code:        "MN",
			Code3:       "MNG",
			NumericCode: "496",
			IsActive:    true,
		},
		{
			Name:        "Nepal",
			Code:        "NP",
			Code3:       "NPL",
			NumericCode: "524",
			IsActive:    true,
		},
		{
			Name:        "Bangladesh",
			Code:        "BD",
			Code3:       "BGD",
			NumericCode: "050",
			IsActive:    true,
		},
		{
			Name:        "Sri Lanka",
			Code:        "LK",
			Code3:       "LKA",
			NumericCode: "144",
			IsActive:    true,
		},
		{
			Name:        "Pakistan",
			Code:        "PK",
			Code3:       "PAK",
			NumericCode: "586",
			IsActive:    true,
		},
		{
			Name:        "Afghanistan",
			Code:        "AF",
			Code3:       "AFG",
			NumericCode: "004",
			IsActive:    true,
		},
		{
			Name:        "Bhutan",
			Code:        "BT",
			Code3:       "BTN",
			NumericCode: "064",
			IsActive:    true,
		},
		{
			Name:        "Maldives",
			Code:        "MV",
			Code3:       "MDV",
			NumericCode: "462",
			IsActive:    true,
		},
		{
			Name:        "Papua New Guinea",
			Code:        "PG",
			Code3:       "PNG",
			NumericCode: "598",
			IsActive:    true,
		},
		{
			Name:        "Fiji",
			Code:        "FJ",
			Code3:       "FJI",
			NumericCode: "242",
			IsActive:    true,
		},
		{
			Name:        "Solomon Islands",
			Code:        "SB",
			Code3:       "SLB",
			NumericCode: "090",
			IsActive:    true,
		},
		{
			Name:        "Samoa",
			Code:        "WS",
			Code3:       "WSM",
			NumericCode: "882",
			IsActive:    true,
		},
		{
			Name:        "Tonga",
			Code:        "TO",
			Code3:       "TON",
			NumericCode: "776",
			IsActive:    true,
		},
		{
			Name:        "Vanuatu",
			Code:        "VU",
			Code3:       "VUT",
			NumericCode: "548",
			IsActive:    true,
		},
		{
			Name:        "Micronesia",
			Code:        "FM",
			Code3:       "FSM",
			NumericCode: "583",
			IsActive:    true,
		},
		{
			Name:        "Palau",
			Code:        "PW",
			Code3:       "PLW",
			NumericCode: "585",
			IsActive:    true,
		},
		{
			Name:        "Nauru",
			Code:        "NR",
			Code3:       "NRU",
			NumericCode: "520",
			IsActive:    true,
		},
		{
			Name:        "Tuvalu",
			Code:        "TV",
			Code3:       "TUV",
			NumericCode: "798",
			IsActive:    true,
		},
		{
			Name:        "Marshall Islands",
			Code:        "MH",
			Code3:       "MHL",
			NumericCode: "584",
			IsActive:    true,
		},
		{
			Name:        "Kiribati",
			Code:        "KI",
			Code3:       "KIR",
			NumericCode: "296",
			IsActive:    true,
		},
		{
			Name:        "Italy",
			Code:        "IT",
			Code3:       "ITA",
			NumericCode: "380",
			IsActive:    true,
		},
		{
			Name:        "Spain",
			Code:        "ES",
			Code3:       "ESP",
			NumericCode: "724",
			IsActive:    true,
		},
		{
			Name:        "Portugal",
			Code:        "PT",
			Code3:       "PRT",
			NumericCode: "620",
			IsActive:    true,
		},
		{
			Name:        "Netherlands",
			Code:        "NL",
			Code3:       "NLD",
			NumericCode: "528",
			IsActive:    true,
		},
		{
			Name:        "Belgium",
			Code:        "BE",
			Code3:       "BEL",
			NumericCode: "056",
			IsActive:    true,
		},
		{
			Name:        "Switzerland",
			Code:        "CH",
			Code3:       "CHE",
			NumericCode: "756",
			IsActive:    true,
		},
		{
			Name:        "Austria",
			Code:        "AT",
			Code3:       "AUT",
			NumericCode: "040",
			IsActive:    true,
		},
		{
			Name:        "Sweden",
			Code:        "SE",
			Code3:       "SWE",
			NumericCode: "752",
			IsActive:    true,
		},
		{
			Name:        "Norway",
			Code:        "NO",
			Code3:       "NOR",
			NumericCode: "578",
			IsActive:    true,
		},
		{
			Name:        "Denmark",
			Code:        "DK",
			Code3:       "DNK",
			NumericCode: "208",
			IsActive:    true,
		},
		{
			Name:        "Finland",
			Code:        "FI",
			Code3:       "FIN",
			NumericCode: "246",
			IsActive:    true,
		},
		{
			Name:        "Poland",
			Code:        "PL",
			Code3:       "POL",
			NumericCode: "616",
			IsActive:    true,
		},
		{
			Name:        "Czech Republic",
			Code:        "CZ",
			Code3:       "CZE",
			NumericCode: "203",
			IsActive:    true,
		},
		{
			Name:        "Hungary",
			Code:        "HU",
			Code3:       "HUN",
			NumericCode: "348",
			IsActive:    true,
		},
		{
			Name:        "Greece",
			Code:        "GR",
			Code3:       "GRC",
			NumericCode: "300",
			IsActive:    true,
		},
		{
			Name:        "Turkey",
			Code:        "TR",
			Code3:       "TUR",
			NumericCode: "792",
			IsActive:    true,
		},
		{
			Name:        "Egypt",
			Code:        "EG",
			Code3:       "EGY",
			NumericCode: "818",
			IsActive:    true,
		},
		{
			Name:        "South Africa",
			Code:        "ZA",
			Code3:       "ZAF",
			NumericCode: "710",
			IsActive:    true,
		},
		{
			Name:        "Nigeria",
			Code:        "NG",
			Code3:       "NGA",
			NumericCode: "566",
			IsActive:    true,
		},
		{
			Name:        "Kenya",
			Code:        "KE",
			Code3:       "KEN",
			NumericCode: "404",
			IsActive:    true,
		},
		{
			Name:        "Ghana",
			Code:        "GH",
			Code3:       "GHA",
			NumericCode: "288",
			IsActive:    true,
		},
		{
			Name:        "Morocco",
			Code:        "MA",
			Code3:       "MAR",
			NumericCode: "504",
			IsActive:    true,
		},
		{
			Name:        "Algeria",
			Code:        "DZ",
			Code3:       "DZA",
			NumericCode: "012",
			IsActive:    true,
		},
		{
			Name:        "Tunisia",
			Code:        "TN",
			Code3:       "TUN",
			NumericCode: "788",
			IsActive:    true,
		},
		{
			Name:        "Ethiopia",
			Code:        "ET",
			Code3:       "ETH",
			NumericCode: "231",
			IsActive:    true,
		},
		{
			Name:        "Argentina",
			Code:        "AR",
			Code3:       "ARG",
			NumericCode: "032",
			IsActive:    true,
		},
		{
			Name:        "Chile",
			Code:        "CL",
			Code3:       "CHL",
			NumericCode: "152",
			IsActive:    true,
		},
		{
			Name:        "Colombia",
			Code:        "CO",
			Code3:       "COL",
			NumericCode: "170",
			IsActive:    true,
		},
		{
			Name:        "Peru",
			Code:        "PE",
			Code3:       "PER",
			NumericCode: "604",
			IsActive:    true,
		},
		{
			Name:        "Venezuela",
			Code:        "VE",
			Code3:       "VEN",
			NumericCode: "862",
			IsActive:    true,
		},
		{
			Name:        "Mexico",
			Code:        "MX",
			Code3:       "MEX",
			NumericCode: "484",
			IsActive:    true,
		},
		{
			Name:        "New Zealand",
			Code:        "NZ",
			Code3:       "NZL",
			NumericCode: "554",
			IsActive:    true,
		},
		{
			Name:        "Saudi Arabia",
			Code:        "SA",
			Code3:       "SAU",
			NumericCode: "682",
			IsActive:    true,
		},
		{
			Name:        "UAE",
			Code:        "AE",
			Code3:       "ARE",
			NumericCode: "784",
			IsActive:    true,
		},
		{
			Name:        "Qatar",
			Code:        "QA",
			Code3:       "QAT",
			NumericCode: "634",
			IsActive:    true,
		},
		{
			Name:        "Israel",
			Code:        "IL",
			Code3:       "ISR",
			NumericCode: "376",
			IsActive:    true,
		},
		{
			Name:        "Jordan",
			Code:        "JO",
			Code3:       "JOR",
			NumericCode: "400",
			IsActive:    true,
		},
		{
			Name:        "Lebanon",
			Code:        "LB",
			Code3:       "LBN",
			NumericCode: "422",
			IsActive:    true,
		},
		{
			Name:        "Iraq",
			Code:        "IQ",
			Code3:       "IRQ",
			NumericCode: "368",
			IsActive:    true,
		},
		{
			Name:        "Iran",
			Code:        "IR",
			Code3:       "IRN",
			NumericCode: "364",
			IsActive:    true,
		},
		{
			Name:        "Syria",
			Code:        "SY",
			Code3:       "SYR",
			NumericCode: "760",
			IsActive:    true,
		},
		{
			Name:        "Yemen",
			Code:        "YE",
			Code3:       "YEM",
			NumericCode: "887",
			IsActive:    true,
		},
		{
			Name:        "Oman",
			Code:        "OM",
			Code3:       "OMN",
			NumericCode: "512",
			IsActive:    true,
		},
		{
			Name:        "Kuwait",
			Code:        "KW",
			Code3:       "KWT",
			NumericCode: "414",
			IsActive:    true,
		},
		{
			Name:        "Bahrain",
			Code:        "BH",
			Code3:       "BHR",
			NumericCode: "048",
			IsActive:    true,
		},
		{
			Name:        "Cyprus",
			Code:        "CY",
			Code3:       "CYP",
			NumericCode: "196",
			IsActive:    true,
		},
		{
			Name:        "Georgia",
			Code:        "GE",
			Code3:       "GEO",
			NumericCode: "268",
			IsActive:    true,
		},
		{
			Name:        "Armenia",
			Code:        "AM",
			Code3:       "ARM",
			NumericCode: "051",
			IsActive:    true,
		},
		{
			Name:        "Azerbaijan",
			Code:        "AZ",
			Code3:       "AZE",
			NumericCode: "031",
			IsActive:    true,
		},
		{
			Name:        "Kazakhstan",
			Code:        "KZ",
			Code3:       "KAZ",
			NumericCode: "398",
			IsActive:    true,
		},
		{
			Name:        "Uzbekistan",
			Code:        "UZ",
			Code3:       "UZB",
			NumericCode: "860",
			IsActive:    true,
		},
		{
			Name:        "Turkmenistan",
			Code:        "TM",
			Code3:       "TKM",
			NumericCode: "795",
			IsActive:    true,
		},
		{
			Name:        "Kyrgyzstan",
			Code:        "KG",
			Code3:       "KGZ",
			NumericCode: "417",
			IsActive:    true,
		},
		{
			Name:        "Tajikistan",
			Code:        "TJ",
			Code3:       "TJK",
			NumericCode: "762",
			IsActive:    true,
		},
		{
			Name:        "North Korea",
			Code:        "KP",
			Code3:       "PRK",
			NumericCode: "408",
			IsActive:    true,
		},
		{
			Name:        "Taiwan",
			Code:        "TW",
			Code3:       "TWN",
			NumericCode: "158",
			IsActive:    true,
		},
		{
			Name:        "Hong Kong",
			Code:        "HK",
			Code3:       "HKG",
			NumericCode: "344",
			IsActive:    true,
		},
		{
			Name:        "Macau",
			Code:        "MO",
			Code3:       "MAC",
			NumericCode: "446",
			IsActive:    true,
		},
		{
			Name:        "Palestine",
			Code:        "PS",
			Code3:       "PSE",
			NumericCode: "275",
			IsActive:    true,
		},
		{
			Name:        "Luxembourg",
			Code:        "LU",
			Code3:       "LUX",
			NumericCode: "442",
			IsActive:    true,
		},
		{
			Name:        "Liechtenstein",
			Code:        "LI",
			Code3:       "LIE",
			NumericCode: "438",
			IsActive:    true,
		},
		{
			Name:        "Monaco",
			Code:        "MC",
			Code3:       "MCO",
			NumericCode: "492",
			IsActive:    true,
		},
		{
			Name:        "San Marino",
			Code:        "SM",
			Code3:       "SMR",
			NumericCode: "674",
			IsActive:    true,
		},
		{
			Name:        "Andorra",
			Code:        "AD",
			Code3:       "AND",
			NumericCode: "020",
			IsActive:    true,
		},
		{
			Name:        "Vatican City",
			Code:        "VA",
			Code3:       "VAT",
			NumericCode: "336",
			IsActive:    true,
		},
		{
			Name:        "Malta",
			Code:        "MT",
			Code3:       "MLT",
			NumericCode: "470",
			IsActive:    true,
		},
		{
			Name:        "Iceland",
			Code:        "IS",
			Code3:       "ISL",
			NumericCode: "352",
			IsActive:    true,
		},
		{
			Name:        "Greenland",
			Code:        "GL",
			Code3:       "GRL",
			NumericCode: "304",
			IsActive:    true,
		},
		{
			Name:        "Faroe Islands",
			Code:        "FO",
			Code3:       "FRO",
			NumericCode: "234",
			IsActive:    true,
		},
		{
			Name:        "Gibraltar",
			Code:        "GI",
			Code3:       "GIB",
			NumericCode: "292",
			IsActive:    true,
		},
		{
			Name:        "Guernsey",
			Code:        "GG",
			Code3:       "GGY",
			NumericCode: "831",
			IsActive:    true,
		},
		{
			Name:        "Jersey",
			Code:        "JE",
			Code3:       "JEY",
			NumericCode: "832",
			IsActive:    true,
		},
		{
			Name:        "Isle of Man",
			Code:        "IM",
			Code3:       "IMN",
			NumericCode: "833",
			IsActive:    true,
		},
		{
			Name:        "Bermuda",
			Code:        "BM",
			Code3:       "BMU",
			NumericCode: "060",
			IsActive:    true,
		},
		{
			Name:        "Cayman Islands",
			Code:        "KY",
			Code3:       "CYM",
			NumericCode: "136",
			IsActive:    true,
		},
		{
			Name:        "Bahamas",
			Code:        "BS",
			Code3:       "BHS",
			NumericCode: "044",
			IsActive:    true,
		},
		{
			Name:        "Barbados",
			Code:        "BB",
			Code3:       "BRB",
			NumericCode: "052",
			IsActive:    true,
		},
		{
			Name:        "Trinidad and Tobago",
			Code:        "TT",
			Code3:       "TTO",
			NumericCode: "780",
			IsActive:    true,
		},
		{
			Name:        "Jamaica",
			Code:        "JM",
			Code3:       "JAM",
			NumericCode: "388",
			IsActive:    true,
		},
		{
			Name:        "Dominica",
			Code:        "DM",
			Code3:       "DMA",
			NumericCode: "212",
			IsActive:    true,
		},
		{
			Name:        "Saint Kitts and Nevis",
			Code:        "KN",
			Code3:       "KNA",
			NumericCode: "659",
			IsActive:    true,
		},
		{
			Name:        "Dominica",
			Code:        "DM",
			Code3:       "DMA",
			NumericCode: "212",
			IsActive:    true,
		},
		{
			Name:        "Saint Lucia",
			Code:        "LC",
			Code3:       "LCA",
			NumericCode: "662",
			IsActive:    true,
		},
		{
			Name:        "Puerto Rico",
			Code:        "PR",
			Code3:       "PRI",
			NumericCode: "630",
			IsActive:    true,
		},
		{
			Name:        "Cuba",
			Code:        "CU",
			Code3:       "CUB",
			NumericCode: "192",
			IsActive:    true,
		},
		{
			Name:        "French Guiana",
			Code:        "GF",
			Code3:       "GUF",
			NumericCode: "254",
			IsActive:    true,
		},
		{
			Name:        "Guyana",
			Code:        "GY",
			Code3:       "GUY",
			NumericCode: "328",
			IsActive:    true,
		},
		{
			Name:        "Suriname",
			Code:        "SR",
			Code3:       "SUR",
			NumericCode: "740",
			IsActive:    true,
		},
		{
			Name:        "Falkland Islands",
			Code:        "FK",
			Code3:       "FLK",
			NumericCode: "238",
			IsActive:    true,
		},
		{
			Name:        "Paraguay",
			Code:        "PY",
			Code3:       "PRY",
			NumericCode: "600",
			IsActive:    true,
		},
		{
			Name:        "Uruguay",
			Code:        "UY",
			Code3:       "URY",
			NumericCode: "858",
			IsActive:    true,
		},
		{
			Name:        "Bolivia",
			Code:        "BO",
			Code3:       "BOL",
			NumericCode: "068",
			IsActive:    true,
		},
		{
			Name:        "Ecuador",
			Code:        "EC",
			Code3:       "ECU",
			NumericCode: "218",
			IsActive:    true,
		},
		{
			Name:        "Panama",
			Code:        "PA",
			Code3:       "PAN",
			NumericCode: "591",
			IsActive:    true,
		},
		{
			Name:        "Costa Rica",
			Code:        "CR",
			Code3:       "CRI",
			NumericCode: "188",
			IsActive:    true,
		},
		{
			Name:        "Nicaragua",
			Code:        "NI",
			Code3:       "NIC",
			NumericCode: "558",
			IsActive:    true,
		},
		{
			Name:        "Honduras",
			Code:        "HN",
			Code3:       "HND",
			NumericCode: "340",
			IsActive:    true,
		},
		{
			Name:        "El Salvador",
			Code:        "SV",
			Code3:       "SLV",
			NumericCode: "222",
			IsActive:    true,
		},
		{
			Name:        "Guatemala",
			Code:        "GT",
			Code3:       "GTM",
			NumericCode: "320",
			IsActive:    true,
		},
		{
			Name:        "Argentina",
			Code:        "AR",
			Code3:       "ARG",
			NumericCode: "032",
			IsActive:    true,
		},
		{
			Name:        "Angola",
			Code:        "AO",
			Code3:       "AGO",
			NumericCode: "024",
			IsActive:    true,
		},
		{
			Name:        "Cameroon",
			Code:        "CM",
			Code3:       "CMR",
			NumericCode: "120",
			IsActive:    true,
		},
		{
			Name:        "Senegal",
			Code:        "SN",
			Code3:       "SEN",
			NumericCode: "686",
			IsActive:    true,
		},
		{
			Name:        "Tanzania",
			Code:        "TZ",
			Code3:       "TZA",
			NumericCode: "834",
			IsActive:    true,
		},
		{
			Name:        "Uganda",
			Code:        "UG",
			Code3:       "UGA",
			NumericCode: "800",
			IsActive:    true,
		},
		{
			Name:        "Mozambique",
			Code:        "MZ",
			Code3:       "MOZ",
			NumericCode: "508",
			IsActive:    true,
		},
		{
			Name:        "Zambia",
			Code:        "ZM",
			Code3:       "ZMB",
			NumericCode: "894",
			IsActive:    true,
		},
		{
			Name:        "Zimbabwe",
			Code:        "ZW",
			Code3:       "ZWE",
			NumericCode: "716",
			IsActive:    true,
		},
		{
			Name:        "Botswana",
			Code:        "BW",
			Code3:       "BWA",
			NumericCode: "072",
			IsActive:    true,
		},
		{
			Name:        "Namibia",
			Code:        "NA",
			Code3:       "NAM",
			NumericCode: "516",
			IsActive:    true,
		},
		{
			Name:        "Madagascar",
			Code:        "MG",
			Code3:       "MDG",
			NumericCode: "450",
			IsActive:    true,
		},
		{
			Name:        "Malawi",
			Code:        "MW",
			Code3:       "MWI",
			NumericCode: "454",
			IsActive:    true,
		},
		{
			Name:        "Rwanda",
			Code:        "RW",
			Code3:       "RWA",
			NumericCode: "646",
			IsActive:    true,
		},
		{
			Name:        "Burundi",
			Code:        "BI",
			Code3:       "BDI",
			NumericCode: "108",
			IsActive:    true,
		},
		{
			Name:        "South Sudan",
			Code:        "SS",
			Code3:       "SSD",
			NumericCode: "728",
			IsActive:    true,
		},
		{
			Name:        "Sudan",
			Code:        "SD",
			Code3:       "SDN",
			NumericCode: "729",
			IsActive:    true,
		},
		{
			Name:        "Chad",
			Code:        "TD",
			Code3:       "TCD",
			NumericCode: "148",
			IsActive:    true,
		},
		{
			Name:        "Niger",
			Code:        "NE",
			Code3:       "NER",
			NumericCode: "562",
			IsActive:    true,
		},
		{
			Name:        "Mali",
			Code:        "ML",
			Code3:       "MLI",
			NumericCode: "466",
			IsActive:    true,
		},
		{
			Name:        "Burkina Faso",
			Code:        "BF",
			Code3:       "BFA",
			NumericCode: "854",
			IsActive:    true,
		},
		{
			Name:        "Benin",
			Code:        "BJ",
			Code3:       "BEN",
			NumericCode: "204",
			IsActive:    true,
		},
		{
			Name:        "Togo",
			Code:        "TG",
			Code3:       "TGO",
			NumericCode: "768",
			IsActive:    true,
		},
		{
			Name:        "Sierra Leone",
			Code:        "SL",
			Code3:       "SLE",
			NumericCode: "694",
			IsActive:    true,
		},
		{
			Name:        "Liberia",
			Code:        "LR",
			Code3:       "LBR",
			NumericCode: "430",
			IsActive:    true,
		},
		{
			Name:        "Congo",
			Code:        "CG",
			Code3:       "COG",
			NumericCode: "178",
			IsActive:    true,
		},
		{
			Name:        "DR Congo",
			Code:        "CD",
			Code3:       "COD",
			NumericCode: "180",
			IsActive:    true,
		},
		{
			Name:        "Gabon",
			Code:        "GA",
			Code3:       "GAB",
			NumericCode: "266",
			IsActive:    true,
		},
		{
			Name:        "Equatorial Guinea",
			Code:        "GQ",
			Code3:       "GNQ",
			NumericCode: "226",
			IsActive:    true,
		},
		{
			Name:        "Central African Republic",
			Code:        "CF",
			Code3:       "CAF",
			NumericCode: "140",
			IsActive:    true,
		},
		{
			Name:        "Eritrea",
			Code:        "ER",
			Code3:       "ERI",
			NumericCode: "232",
			IsActive:    true,
		},
		{
			Name:        "Djibouti",
			Code:        "DJ",
			Code3:       "DJI",
			NumericCode: "262",
			IsActive:    true,
		},
		{
			Name:        "Somalia",
			Code:        "SO",
			Code3:       "SOM",
			NumericCode: "706",
			IsActive:    true,
		},
		{
			Name:        "Lesotho",
			Code:        "LS",
			Code3:       "LSO",
			NumericCode: "426",
			IsActive:    true,
		},
		{
			Name:        "Eswatini",
			Code:        "SZ",
			Code3:       "SWZ",
			NumericCode: "748",
			IsActive:    true,
		},
		{
			Name:        "Gambia",
			Code:        "GM",
			Code3:       "GMB",
			NumericCode: "270",
			IsActive:    true,
		},
		{
			Name:        "Guinea",
			Code:        "GN",
			Code3:       "GIN",
			NumericCode: "324",
			IsActive:    true,
		},
		{
			Name:        "Guinea-Bissau",
			Code:        "GW",
			Code3:       "GNB",
			NumericCode: "624",
			IsActive:    true,
		},
		{
			Name:        "Mauritania",
			Code:        "MR",
			Code3:       "MRT",
			NumericCode: "478",
			IsActive:    true,
		},
		{
			Name:        "Comoros",
			Code:        "KM",
			Code3:       "COM",
			NumericCode: "174",
			IsActive:    true,
		},
		{
			Name:        "Seychelles",
			Code:        "SC",
			Code3:       "SYC",
			NumericCode: "690",
			IsActive:    true,
		},
		{
			Name:        "Cape Verde",
			Code:        "CV",
			Code3:       "CPV",
			NumericCode: "132",
			IsActive:    true,
		},
		{
			Name:        "Sao Tome and Principe",
			Code:        "ST",
			Code3:       "STP",
			NumericCode: "678",
			IsActive:    true,
		},
		{
			Name:        "Western Sahara",
			Code:        "EH",
			Code3:       "ESH",
			NumericCode: "732",
			IsActive:    true,
		},
		{
			Name:        "Russia",
			Code:        "RU",
			Code3:       "RUS",
			NumericCode: "643",
			IsActive:    true,
		},
		{
			Name:        "Ukraine",
			Code:        "UA",
			Code3:       "UKR",
			NumericCode: "804",
			IsActive:    true,
		},
		{
			Name:        "Belarus",
			Code:        "BY",
			Code3:       "BLR",
			NumericCode: "112",
			IsActive:    true,
		},
		{
			Name:        "Moldova",
			Code:        "MD",
			Code3:       "MDA",
			NumericCode: "498",
			IsActive:    true,
		},
		{
			Name:        "Romania",
			Code:        "RO",
			Code3:       "ROU",
			NumericCode: "642",
			IsActive:    true,
		},
		{
			Name:        "Bulgaria",
			Code:        "BG",
			Code3:       "BGR",
			NumericCode: "100",
			IsActive:    true,
		},
		{
			Name:        "Serbia",
			Code:        "RS",
			Code3:       "SRB",
			NumericCode: "688",
			IsActive:    true,
		},
		{
			Name:        "Croatia",
			Code:        "HR",
			Code3:       "HRV",
			NumericCode: "191",
			IsActive:    true,
		},
		{
			Name:        "Slovenia",
			Code:        "SI",
			Code3:       "SVN",
			NumericCode: "705",
			IsActive:    true,
		},
		{
			Name:        "Slovakia",
			Code:        "SK",
			Code3:       "SVK",
			NumericCode: "703",
			IsActive:    true,
		},
		{
			Name:        "Estonia",
			Code:        "EE",
			Code3:       "EST",
			NumericCode: "233",
			IsActive:    true,
		},
		{
			Name:        "Latvia",
			Code:        "LV",
			Code3:       "LVA",
			NumericCode: "428",
			IsActive:    true,
		},
		{
			Name:        "Lithuania",
			Code:        "LT",
			Code3:       "LTU",
			NumericCode: "440",
			IsActive:    true,
		},
		{
			Name:        "Albania",
			Code:        "AL",
			Code3:       "ALB",
			NumericCode: "008",
			IsActive:    true,
		},
		{
			Name:        "North Macedonia",
			Code:        "MK",
			Code3:       "MKD",
			NumericCode: "807",
			IsActive:    true,
		},
		{
			Name:        "Kosovo",
			Code:        "XK",
			Code3:       "XKX",
			NumericCode: "983",
			IsActive:    true,
		},
		{
			Name:        "Montenegro",
			Code:        "ME",
			Code3:       "MNE",
			NumericCode: "499",
			IsActive:    true,
		},
		{
			Name:        "Bosnia and Herzegovina",
			Code:        "BA",
			Code3:       "BIH",
			NumericCode: "070",
			IsActive:    true,
		},
		{
			Name:        "Iceland",
			Code:        "IS",
			Code3:       "ISL",
			NumericCode: "352",
			IsActive:    true,
		},
		{
			Name:        "Greenland",
			Code:        "GL",
			Code3:       "GRL",
			NumericCode: "304",
			IsActive:    true,
		},
		{
			Name:        "Faroe Islands",
			Code:        "FO",
			Code3:       "FRO",
			NumericCode: "234",
			IsActive:    true,
		},
		{
			Name:        "Gibraltar",
			Code:        "GI",
			Code3:       "GIB",
			NumericCode: "292",
			IsActive:    true,
		},
		{
			Name:        "Guernsey",
			Code:        "GG",
			Code3:       "GGY",
			NumericCode: "831",
			IsActive:    true,
		},
		{
			Name:        "Jersey",
			Code:        "JE",
			Code3:       "JEY",
			NumericCode: "832",
			IsActive:    true,
		},
		{
			Name:        "Isle of Man",
			Code:        "IM",
			Code3:       "IMN",
			NumericCode: "833",
			IsActive:    true,
		},
		{
			Name:        "Bermuda",
			Code:        "BM",
			Code3:       "BMU",
			NumericCode: "060",
			IsActive:    true,
		},
		{
			Name:        "Cayman Islands",
			Code:        "KY",
			Code3:       "CYM",
			NumericCode: "136",
			IsActive:    true,
		},
		{
			Name:        "Bahamas",
			Code:        "BS",
			Code3:       "BHS",
			NumericCode: "044",
			IsActive:    true,
		},
		{
			Name:        "Barbados",
			Code:        "BB",
			Code3:       "BRB",
			NumericCode: "052",
			IsActive:    true,
		},
		{
			Name:        "Trinidad and Tobago",
			Code:        "TT",
			Code3:       "TTO",
			NumericCode: "780",
			IsActive:    true,
		},
		{
			Name:        "Jamaica",
			Code:        "JM",
			Code3:       "JAM",
			NumericCode: "388",
			IsActive:    true,
		},
		{
			Name:        "Dominica",
			Code:        "DM",
			Code3:       "DMA",
			NumericCode: "212",
			IsActive:    true,
		},
		{
			Name:        "Saint Kitts and Nevis",
			Code:        "KN",
			Code3:       "KNA",
			NumericCode: "659",
			IsActive:    true,
		},
		{
			Name:        "Saint Lucia",
			Code:        "LC",
			Code3:       "LCA",
			NumericCode: "662",
			IsActive:    true,
		},
		{
			Name:        "Puerto Rico",
			Code:        "PR",
			Code3:       "PRI",
			NumericCode: "630",
			IsActive:    true,
		},
		{
			Name:        "Cuba",
			Code:        "CU",
			Code3:       "CUB",
			NumericCode: "192",
			IsActive:    true,
		},
		{
			Name:        "French Guiana",
			Code:        "GF",
			Code3:       "GUF",
			NumericCode: "254",
			IsActive:    true,
		},
		{
			Name:        "Guyana",
			Code:        "GY",
			Code3:       "GUY",
			NumericCode: "328",
			IsActive:    true,
		},
		{
			Name:        "Suriname",
			Code:        "SR",
			Code3:       "SUR",
			NumericCode: "740",
			IsActive:    true,
		},
		{
			Name:        "Falkland Islands",
			Code:        "FK",
			Code3:       "FLK",
			NumericCode: "238",
			IsActive:    true,
		},
		{
			Name:        "Paraguay",
			Code:        "PY",
			Code3:       "PRY",
			NumericCode: "600",
			IsActive:    true,
		},
		{
			Name:        "Uruguay",
			Code:        "UY",
			Code3:       "URY",
			NumericCode: "858",
			IsActive:    true,
		},
		{
			Name:        "Bolivia",
			Code:        "BO",
			Code3:       "BOL",
			NumericCode: "068",
			IsActive:    true,
		},
		{
			Name:        "Ecuador",
			Code:        "EC",
			Code3:       "ECU",
			NumericCode: "218",
			IsActive:    true,
		},
		{
			Name:        "Panama",
			Code:        "PA",
			Code3:       "PAN",
			NumericCode: "591",
			IsActive:    true,
		},
		{
			Name:        "Costa Rica",
			Code:        "CR",
			Code3:       "CRI",
			NumericCode: "188",
			IsActive:    true,
		},
		{
			Name:        "Nicaragua",
			Code:        "NI",
			Code3:       "NIC",
			NumericCode: "558",
			IsActive:    true,
		},
		{
			Name:        "Honduras",
			Code:        "HN",
			Code3:       "HND",
			NumericCode: "340",
			IsActive:    true,
		},
		{
			Name:        "El Salvador",
			Code:        "SV",
			Code3:       "SLV",
			NumericCode: "222",
			IsActive:    true,
		},
		{
			Name:        "Guatemala",
			Code:        "GT",
			Code3:       "GTM",
			NumericCode: "320",
			IsActive:    true,
		},
		{
			Name:        "Angola",
			Code:        "AO",
			Code3:       "AGO",
			NumericCode: "024",
			IsActive:    true,
		},
		{
			Name:        "Cameroon",
			Code:        "CM",
			Code3:       "CMR",
			NumericCode: "120",
			IsActive:    true,
		},
		{
			Name:        "Senegal",
			Code:        "SN",
			Code3:       "SEN",
			NumericCode: "686",
			IsActive:    true,
		},
		{
			Name:        "Tanzania",
			Code:        "TZ",
			Code3:       "TZA",
			NumericCode: "834",
			IsActive:    true,
		},
		{
			Name:        "Uganda",
			Code:        "UG",
			Code3:       "UGA",
			NumericCode: "800",
			IsActive:    true,
		},
		{
			Name:        "Mozambique",
			Code:        "MZ",
			Code3:       "MOZ",
			NumericCode: "508",
			IsActive:    true,
		},
		{
			Name:        "Zambia",
			Code:        "ZM",
			Code3:       "ZMB",
			NumericCode: "894",
			IsActive:    true,
		},
		{
			Name:        "Zimbabwe",
			Code:        "ZW",
			Code3:       "ZWE",
			NumericCode: "716",
			IsActive:    true,
		},
		{
			Name:        "Botswana",
			Code:        "BW",
			Code3:       "BWA",
			NumericCode: "072",
			IsActive:    true,
		},
		{
			Name:        "Namibia",
			Code:        "NA",
			Code3:       "NAM",
			NumericCode: "516",
			IsActive:    true,
		},
		{
			Name:        "Madagascar",
			Code:        "MG",
			Code3:       "MDG",
			NumericCode: "450",
			IsActive:    true,
		},
		{
			Name:        "Malawi",
			Code:        "MW",
			Code3:       "MWI",
			NumericCode: "454",
			IsActive:    true,
		},
		{
			Name:        "Rwanda",
			Code:        "RW",
			Code3:       "RWA",
			NumericCode: "646",
			IsActive:    true,
		},
		{
			Name:        "Burundi",
			Code:        "BI",
			Code3:       "BDI",
			NumericCode: "108",
			IsActive:    true,
		},
		{
			Name:        "South Sudan",
			Code:        "SS",
			Code3:       "SSD",
			NumericCode: "728",
			IsActive:    true,
		},
		{
			Name:        "Sudan",
			Code:        "SD",
			Code3:       "SDN",
			NumericCode: "729",
			IsActive:    true,
		},
		{
			Name:        "Chad",
			Code:        "TD",
			Code3:       "TCD",
			NumericCode: "148",
			IsActive:    true,
		},
		{
			Name:        "Niger",
			Code:        "NE",
			Code3:       "NER",
			NumericCode: "562",
			IsActive:    true,
		},
		{
			Name:        "Mali",
			Code:        "ML",
			Code3:       "MLI",
			NumericCode: "466",
			IsActive:    true,
		},
		{
			Name:        "Burkina Faso",
			Code:        "BF",
			Code3:       "BFA",
			NumericCode: "854",
			IsActive:    true,
		},
		{
			Name:        "Benin",
			Code:        "BJ",
			Code3:       "BEN",
			NumericCode: "204",
			IsActive:    true,
		},
		{
			Name:        "Togo",
			Code:        "TG",
			Code3:       "TGO",
			NumericCode: "768",
			IsActive:    true,
		},
		{
			Name:        "Sierra Leone",
			Code:        "SL",
			Code3:       "SLE",
			NumericCode: "694",
			IsActive:    true,
		},
		{
			Name:        "Liberia",
			Code:        "LR",
			Code3:       "LBR",
			NumericCode: "430",
			IsActive:    true,
		},
		{
			Name:        "Congo",
			Code:        "CG",
			Code3:       "COG",
			NumericCode: "178",
			IsActive:    true,
		},
		{
			Name:        "DR Congo",
			Code:        "CD",
			Code3:       "COD",
			NumericCode: "180",
			IsActive:    true,
		},
		{
			Name:        "Gabon",
			Code:        "GA",
			Code3:       "GAB",
			NumericCode: "266",
			IsActive:    true,
		},
		{
			Name:        "Equatorial Guinea",
			Code:        "GQ",
			Code3:       "GNQ",
			NumericCode: "226",
			IsActive:    true,
		},
		{
			Name:        "Central African Republic",
			Code:        "CF",
			Code3:       "CAF",
			NumericCode: "140",
			IsActive:    true,
		},
		{
			Name:        "Eritrea",
			Code:        "ER",
			Code3:       "ERI",
			NumericCode: "232",
			IsActive:    true,
		},
		{
			Name:        "Djibouti",
			Code:        "DJ",
			Code3:       "DJI",
			NumericCode: "262",
			IsActive:    true,
		},
		{
			Name:        "Somalia",
			Code:        "SO",
			Code3:       "SOM",
			NumericCode: "706",
			IsActive:    true,
		},
		{
			Name:        "Lesotho",
			Code:        "LS",
			Code3:       "LSO",
			NumericCode: "426",
			IsActive:    true,
		},
		{
			Name:        "Eswatini",
			Code:        "SZ",
			Code3:       "SWZ",
			NumericCode: "748",
			IsActive:    true,
		},
		{
			Name:        "Gambia",
			Code:        "GM",
			Code3:       "GMB",
			NumericCode: "270",
			IsActive:    true,
		},
		{
			Name:        "Guinea",
			Code:        "GN",
			Code3:       "GIN",
			NumericCode: "324",
			IsActive:    true,
		},
		{
			Name:        "Guinea-Bissau",
			Code:        "GW",
			Code3:       "GNB",
			NumericCode: "624",
			IsActive:    true,
		},
		{
			Name:        "Mauritania",
			Code:        "MR",
			Code3:       "MRT",
			NumericCode: "478",
			IsActive:    true,
		},
		{
			Name:        "Comoros",
			Code:        "KM",
			Code3:       "COM",
			NumericCode: "174",
			IsActive:    true,
		},
		{
			Name:        "Seychelles",
			Code:        "SC",
			Code3:       "SYC",
			NumericCode: "690",
			IsActive:    true,
		},
		{
			Name:        "Cape Verde",
			Code:        "CV",
			Code3:       "CPV",
			NumericCode: "132",
			IsActive:    true,
		},
		{
			Name:        "Sao Tome and Principe",
			Code:        "ST",
			Code3:       "STP",
			NumericCode: "678",
			IsActive:    true,
		},
		{
			Name:        "Western Sahara",
			Code:        "EH",
			Code3:       "ESH",
			NumericCode: "732",
			IsActive:    true,
		},
		{
			Name:        "Russia",
			Code:        "RU",
			Code3:       "RUS",
			NumericCode: "643",
			IsActive:    true,
		},
		{
			Name:        "Ukraine",
			Code:        "UA",
			Code3:       "UKR",
			NumericCode: "804",
			IsActive:    true,
		},
		{
			Name:        "Belarus",
			Code:        "BY",
			Code3:       "BLR",
			NumericCode: "112",
			IsActive:    true,
		},
		{
			Name:        "Moldova",
			Code:        "MD",
			Code3:       "MDA",
			NumericCode: "498",
			IsActive:    true,
		},
		{
			Name:        "Romania",
			Code:        "RO",
			Code3:       "ROU",
			NumericCode: "642",
			IsActive:    true,
		},
		{
			Name:        "Bulgaria",
			Code:        "BG",
			Code3:       "BGR",
			NumericCode: "100",
			IsActive:    true,
		},
		{
			Name:        "Serbia",
			Code:        "RS",
			Code3:       "SRB",
			NumericCode: "688",
			IsActive:    true,
		},
		{
			Name:        "Croatia",
			Code:        "HR",
			Code3:       "HRV",
			NumericCode: "191",
			IsActive:    true,
		},
		{
			Name:        "Slovenia",
			Code:        "SI",
			Code3:       "SVN",
			NumericCode: "705",
			IsActive:    true,
		},
		{
			Name:        "Slovakia",
			Code:        "SK",
			Code3:       "SVK",
			NumericCode: "703",
			IsActive:    true,
		},
		{
			Name:        "Estonia",
			Code:        "EE",
			Code3:       "EST",
			NumericCode: "233",
			IsActive:    true,
		},
		{
			Name:        "Latvia",
			Code:        "LV",
			Code3:       "LVA",
			NumericCode: "428",
			IsActive:    true,
		},
		{
			Name:        "Lithuania",
			Code:        "LT",
			Code3:       "LTU",
			NumericCode: "440",
			IsActive:    true,
		},
		{
			Name:        "Albania",
			Code:        "AL",
			Code3:       "ALB",
			NumericCode: "008",
			IsActive:    true,
		},
		{
			Name:        "North Macedonia",
			Code:        "MK",
			Code3:       "MKD",
			NumericCode: "807",
			IsActive:    true,
		},
		{
			Name:        "Kosovo",
			Code:        "XK",
			Code3:       "XKX",
			NumericCode: "983",
			IsActive:    true,
		},
		{
			Name:        "Montenegro",
			Code:        "ME",
			Code3:       "MNE",
			NumericCode: "499",
			IsActive:    true,
		},
		{
			Name:        "Bosnia and Herzegovina",
			Code:        "BA",
			Code3:       "BIH",
			NumericCode: "070",
			IsActive:    true,
		},
		{
			Name:        "Saint Vincent and the Grenadines",
			Code:        "VC",
			Code3:       "VCT",
			NumericCode: "670",
			IsActive:    true,
		},
		{
			Name:        "Grenada",
			Code:        "GD",
			Code3:       "GRD",
			NumericCode: "308",
			IsActive:    true,
		},
		{
			Name:        "Antigua and Barbuda",
			Code:        "AG",
			Code3:       "ATG",
			NumericCode: "028",
			IsActive:    true,
		},
		{
			Name:        "Saint Kitts and Nevis",
			Code:        "KN",
			Code3:       "KNA",
			NumericCode: "659",
			IsActive:    true,
		},
		{
			Name:        "Haiti",
			Code:        "HT",
			Code3:       "HTI",
			NumericCode: "332",
			IsActive:    true,
		},
		{
			Name:        "Dominican Republic",
			Code:        "DO",
			Code3:       "DOM",
			NumericCode: "214",
			IsActive:    true,
		},
		{
			Name:        "Belize",
			Code:        "BZ",
			Code3:       "BLZ",
			NumericCode: "084",
			IsActive:    true,
		},
		{
			Name:        "Honduras",
			Code:        "HN",
			Code3:       "HND",
			NumericCode: "340",
			IsActive:    true,
		},
		{
			Name:        "El Salvador",
			Code:        "SV",
			Code3:       "SLV",
			NumericCode: "222",
			IsActive:    true,
		},
		{
			Name:        "Guatemala",
			Code:        "GT",
			Code3:       "GTM",
			NumericCode: "320",
			IsActive:    true,
		},
		{
			Name:        "Nicaragua",
			Code:        "NI",
			Code3:       "NIC",
			NumericCode: "558",
			IsActive:    true,
		},
		{
			Name:        "Costa Rica",
			Code:        "CR",
			Code3:       "CRI",
			NumericCode: "188",
			IsActive:    true,
		},
		{
			Name:        "Panama",
			Code:        "PA",
			Code3:       "PAN",
			NumericCode: "591",
			IsActive:    true,
		},
		{
			Name:        "Colombia",
			Code:        "CO",
			Code3:       "COL",
			NumericCode: "170",
			IsActive:    true,
		},
		{
			Name:        "Venezuela",
			Code:        "VE",
			Code3:       "VEN",
			NumericCode: "862",
			IsActive:    true,
		},
		{
			Name:        "Guyana",
			Code:        "GY",
			Code3:       "GUY",
			NumericCode: "328",
			IsActive:    true,
		},
		{
			Name:        "Suriname",
			Code:        "SR",
			Code3:       "SUR",
			NumericCode: "740",
			IsActive:    true,
		},
		{
			Name:        "French Guiana",
			Code:        "GF",
			Code3:       "GUF",
			NumericCode: "254",
			IsActive:    true,
		},
		{
			Name:        "Falkland Islands",
			Code:        "FK",
			Code3:       "FLK",
			NumericCode: "238",
			IsActive:    true,
		},
		{
			Name:        "Paraguay",
			Code:        "PY",
			Code3:       "PRY",
			NumericCode: "600",
			IsActive:    true,
		},
		{
			Name:        "Uruguay",
			Code:        "UY",
			Code3:       "URY",
			NumericCode: "858",
			IsActive:    true,
		},
		{
			Name:        "Bolivia",
			Code:        "BO",
			Code3:       "BOL",
			NumericCode: "068",
			IsActive:    true,
		},
		{
			Name:        "Ecuador",
			Code:        "EC",
			Code3:       "ECU",
			NumericCode: "218",
			IsActive:    true,
		},
		{
			Name:        "Peru",
			Code:        "PE",
			Code3:       "PER",
			NumericCode: "604",
			IsActive:    true,
		},
		{
			Name:        "Chile",
			Code:        "CL",
			Code3:       "CHL",
			NumericCode: "152",
			IsActive:    true,
		},
		{
			Name:        "Argentina",
			Code:        "AR",
			Code3:       "ARG",
			NumericCode: "032",
			IsActive:    true,
		},
		{
			Name:        "Mexico",
			Code:        "MX",
			Code3:       "MEX",
			NumericCode: "484",
			IsActive:    true,
		},
		{
			Name:        "Cuba",
			Code:        "CU",
			Code3:       "CUB",
			NumericCode: "192",
			IsActive:    true,
		},
		{
			Name:        "Jamaica",
			Code:        "JM",
			Code3:       "JAM",
			NumericCode: "388",
			IsActive:    true,
		},
		{
			Name:        "Haiti",
			Code:        "HT",
			Code3:       "HTI",
			NumericCode: "332",
			IsActive:    true,
		},
		{
			Name:        "Dominican Republic",
			Code:        "DO",
			Code3:       "DOM",
			NumericCode: "214",
			IsActive:    true,
		},
		{
			Name:        "Puerto Rico",
			Code:        "PR",
			Code3:       "PRI",
			NumericCode: "630",
			IsActive:    true,
		},
		{
			Name:        "Bahamas",
			Code:        "BS",
			Code3:       "BHS",
			NumericCode: "044",
			IsActive:    true,
		},
		{
			Name:        "Barbados",
			Code:        "BB",
			Code3:       "BRB",
			NumericCode: "052",
			IsActive:    true,
		},
		{
			Name:        "Trinidad and Tobago",
			Code:        "TT",
			Code3:       "TTO",
			NumericCode: "780",
			IsActive:    true,
		},
		{
			Name:        "Dominica",
			Code:        "DM",
			Code3:       "DMA",
			NumericCode: "212",
			IsActive:    true,
		},
		{
			Name:        "Saint Lucia",
			Code:        "LC",
			Code3:       "LCA",
			NumericCode: "662",
			IsActive:    true,
		},
		{
			Name:        "Saint Vincent and the Grenadines",
			Code:        "VC",
			Code3:       "VCT",
			NumericCode: "670",
			IsActive:    true,
		},
		{
			Name:        "Grenada",
			Code:        "GD",
			Code3:       "GRD",
			NumericCode: "308",
			IsActive:    true,
		},
		{
			Name:        "Antigua and Barbuda",
			Code:        "AG",
			Code3:       "ATG",
			NumericCode: "028",
			IsActive:    true,
		},
		{
			Name:        "Belize",
			Code:        "BZ",
			Code3:       "BLZ",
			NumericCode: "084",
			IsActive:    true,
		},
		{
			Name:        "Bermuda",
			Code:        "BM",
			Code3:       "BMU",
			NumericCode: "060",
			IsActive:    true,
		},
		{
			Name:        "Cayman Islands",
			Code:        "KY",
			Code3:       "CYM",
			NumericCode: "136",
			IsActive:    true,
		},
		{
			Name:        "Greenland",
			Code:        "GL",
			Code3:       "GRL",
			NumericCode: "304",
			IsActive:    true,
		},
		{
			Name:        "Faroe Islands",
			Code:        "FO",
			Code3:       "FRO",
			NumericCode: "234",
			IsActive:    true,
		},
		{
			Name:        "Gibraltar",
			Code:        "GI",
			Code3:       "GIB",
			NumericCode: "292",
			IsActive:    true,
		},
		{
			Name:        "Guernsey",
			Code:        "GG",
			Code3:       "GGY",
			NumericCode: "831",
			IsActive:    true,
		},
		{
			Name:        "Jersey",
			Code:        "JE",
			Code3:       "JEY",
			NumericCode: "832",
			IsActive:    true,
		},
		{
			Name:        "Isle of Man",
			Code:        "IM",
			Code3:       "IMN",
			NumericCode: "833",
			IsActive:    true,
		},
		{
			Name:        "Iceland",
			Code:        "IS",
			Code3:       "ISL",
			NumericCode: "352",
			IsActive:    true,
		},
		{
			Name:        "Luxembourg",
			Code:        "LU",
			Code3:       "LUX",
			NumericCode: "442",
			IsActive:    true,
		},
		{
			Name:        "Liechtenstein",
			Code:        "LI",
			Code3:       "LIE",
			NumericCode: "438",
			IsActive:    true,
		},
		{
			Name:        "Monaco",
			Code:        "MC",
			Code3:       "MCO",
			NumericCode: "492",
			IsActive:    true,
		},
		{
			Name:        "San Marino",
			Code:        "SM",
			Code3:       "SMR",
			NumericCode: "674",
			IsActive:    true,
		},
		{
			Name:        "Andorra",
			Code:        "AD",
			Code3:       "AND",
			NumericCode: "020",
			IsActive:    true,
		},
		{
			Name:        "Vatican City",
			Code:        "VA",
			Code3:       "VAT",
			NumericCode: "336",
			IsActive:    true,
		},
		{
			Name:        "Malta",
			Code:        "MT",
			Code3:       "MLT",
			NumericCode: "470",
			IsActive:    true,
		},
		{
			Name:        "North Korea",
			Code:        "KP",
			Code3:       "PRK",
			NumericCode: "408",
			IsActive:    true,
		},
		{
			Name:        "Taiwan",
			Code:        "TW",
			Code3:       "TWN",
			NumericCode: "158",
			IsActive:    true,
		},
		{
			Name:        "Hong Kong",
			Code:        "HK",
			Code3:       "HKG",
			NumericCode: "344",
			IsActive:    true,
		},
		{
			Name:        "Macau",
			Code:        "MO",
			Code3:       "MAC",
			NumericCode: "446",
			IsActive:    true,
		},
		{
			Name:        "Palestine",
			Code:        "PS",
			Code3:       "PSE",
			NumericCode: "275",
			IsActive:    true,
		},
	}

	// Remove duplicates by country code (keep first occurrence)
	uniqueCountries := make(map[string]bool)
	filteredCountries := make([]models.Country, 0, len(countries))
	for _, country := range countries {
		if !uniqueCountries[country.Code] {
			uniqueCountries[country.Code] = true
			filteredCountries = append(filteredCountries, country)
		}
	}

	// Create countries in database
	seederID := models.USER_SEEDER_ULID
	for _, country := range filteredCountries {
		country.BaseModel = models.BaseModel{
			CreatedBy: &seederID,
			UpdatedBy: &seederID,
			DeletedBy: nil,
		}
		err = facades.Orm().Query().Create(&country)
		if err != nil {
			facades.Log().Error("Failed to create country " + country.Name + ": " + err.Error())
			return err
		}
		facades.Log().Info("Created country: " + country.Name)
	}

	facades.Log().Info("Countries seeded successfully")
	return nil
}
