server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: goravel-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: goravel
          __path__: /var/log/goravel/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: time
            message: msg
            service: service
      - labels:
          level:
          service:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: message 